{% set version = "0.16.12" %}
# The version_info tuple in __init__.py must also be updated

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 076cc0bc34f1966d920a49f18b52b6ad559fbe656a0748e3535cf7b3f29ebf9e

build:
  number: 1
  no_link: .*\.(pyd|dll)  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - posix               # [win]

  host:
    - python
    - pip
    - setuptools
    - cython
    - yaml

  run:
    - python
    - yaml

test:
  requires:
    - pytest

  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.
  
  description: |
    ruamel.yaml is a YAML 1.2 loader/dumper package for Python.
  doc_url: http://yaml.readthedocs.io/en/latest/overview.html
  dev_url: https://bitbucket.org/ruamel/yaml/src
  doc_source_url: https://bitbucket.org/ruamel/yaml/src/default/_doc/?at=default

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
