travis:
  secure:
    BINSTAR_TOKEN: dbw6UJlKm0aS4+U5qBhZ9kadbTiEhbYsEhNlAKNlYuzEgWNk/SxfVJ+61h7IFghvgB86RMgRQdCYpR9ZKPCuQocA5Rfu8zyGLAs3ZlvSK9UIpICYuH08dxQBNwehi1FQH7lw8SieHNEtEDDFwiitPQb8BJY9gctyzo5y9qlkHGbWvB6Qh/IYDZM9/Zz3Uw7Hv9hPKrNPy/cyDuWbagnzk/K70q9hmGF+AYxXwVfzuHx18cggmEy1YN8nA2eJ675G3dTXtBZmaqp3dAhQqjMxuP7G4alwIPimWHyy2rBZcnSvf5qBxxUTq7M62B4/9VdQopAgLvLJfugh9x4OI/cFKDFTHTvc3CyE3z6vornVtQBuYEnUIYrRYZx8dLATRjNbkuLaNQdo56jnqqUYzZtquX1kyBUeJ3hW1o9eDMD61KSxLqEi1O79J2TeiKBCB5EhzZSSRX8+HKON1eYr/+biOP8yIIfWrasEwFimDbycbaJGvCGgmSfpNPDPsf2y0ZJ8sTv9YQiXggRmRseF6jGSw083ejB0Ei0/Zf7Mh/KamDTUFz68OXwtt7SMnFCDP1fTQr3NaLkExmzT7Yu+QByCWYFjJ5zeuyh2BKkpMMChcApR0wWj4NXWynsYoB/Y9dvczYw+OZJly23w0jqh6kr9iqaSQ+C9xdAUbuS1I0QFnBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
